version: '3'

services:

  mysql:
    image: mysql:latest
    command: --init-file /data/application/init.sql
    volumes:
      - ./databases/create_databases.sql:/data/application/init.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      #MYSQL_DATABASE: testapp
    ports:
    - "3308:3306"